### ISSUE TITLE
Mixmir error 

### ISSUE THREAD

**Issue by LliliansCalvo** [ldiao/MixMir#3]
Hi, 
I am trying to run mirmix on a list, rather small, of 3'UTR  from the gene eve in different insects species. However I keep getting the same error and I cannot figure out what's the problem. 

My fasta file looks like : 
>apis_mellifera_eve
GAA....
>bombyx_mori_eve
TTTAGTT..
>drosophila_melanogaster_eve
GCCCGCGA..
(total of 9 different sequences in FASTA format)

My ID ranked files looks like (rank is arbitrary and was created by myself) : 
apis_mellifera_eve 3
bombyx_mori_eve -2
drosophila_melanogaster_eve 4
drosophila_sechillia_eve 4
drosophila_simulans_eve 4
drosophila_yakuba_eve 4
oncopeltus_fasciatus_eve -3
nasonia_vitripennis_eve -1
tribolium_castaneum_eve -2
(total of 9 different UTRs)

I am using microRNA mature sequences downloaded from mirbase: 
>dps-miR-2517a-3p
UAUUG..
>dps-miR-2543a-5p
AUCCUAU..
>dps-miR-2543a-3p
UAUGCA..
>dps-miR-2543b-5p
AUCCUA..

my command is : MixMir-master llilians$ python MixMir.py --seqf  all_utr3p.fa --exprf IDs_ranked.txt --mirf arthropods-mature.fa --k_kin 6 --k_motif 6 --N 20 --fast 0 --out results

Error : Solving MLM with GEMMA
Parsing files for PLINK
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 18, in doAll
    runParse(doKin=doKin)
  File "MixMir.py", line 43, in runParse
    parseAll.doAll(doKin=doKin,seqf=seqf,exprf=exprf,outfnkin=kinf,outPedFile=outPedFile,outMapFile=outMapFile,kkin=kkin,kmotif=kmotif,frac=frac,useFast=useFast)
  File "/Users/llilians/Desktop/MixMir-master/parseAll.py", line 46, in doAll
    exprs = loadmic(fname=exprf)
  File "/Users/llilians/Desktop/MixMir-master/parseAll.py", line 112, in loadmic
    exprs = [[row[0],float(row[1])] for row in exprs]
  File "/Users/llilians/Desktop/MixMir-master/parseAll.py", line 112, in <listcomp>
    exprs = [[row[0],float(row[1])] for row in exprs]
IndexError: list index out of range

Could you please help me to figure out what's the problem here ? 
Thanks,

**Comment by kcchen88** [comment]
Hi, did you by any chance forget a ">" character in your Fasta files?


Kevin

________________________________

**Comment by LliliansCalvo** [comment]
Hi, 
The FASTA file looks fine with the '>'
Here I add a screenshot of my FASTA file 

<img width="1050" alt="screen shot 2017-11-26 at 20 30 02" src="https://user-images.githubusercontent.com/33156274/33244080-c7ed07d0-d2e8-11e7-9ddc-6eb5caa22d5d.png">

The mirbase FASTA file also looks like that containing only the mature sequences. 
Thanks

**Comment by LliliansCalvo** [comment]
Also when I try to run the example from the README file, it doesn't work neither and I get an error message like this : 

l-u-c02sl2h9gg78:MixMir-master llilians$ python MixMir.py --seqf testdat/test-utrs.fa --exprf testdat/test-exprs.txt --mirf testdat/testmirs.fa --k_kin 6 --k_motif 6 --N 20 --fast 0 --out testdat/test
Solving MLM with GEMMA
Parsing files for PLINK
Removing 418 motifs with no information
Removing 418 motifs with no information
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 18, in doAll
    runParse(doKin=doKin)
  File "MixMir.py", line 43, in runParse
    parseAll.doAll(doKin=doKin,seqf=seqf,exprf=exprf,outfnkin=kinf,outPedFile=outPedFile,outMapFile=outMapFile,kkin=kkin,kmotif=kmotif,frac=frac,useFast=useFast)
  File "/Users/llilians/Desktop/MixMir-master/parseAll.py", line 76, in doAll
    makePed(genes=genes,dcounts=dcounts,dexprs=dexprs,outfn=outPedFile)
  File "/Users/llilians/Desktop/MixMir-master/parseAll.py", line 281, in makePed
    newrow = [g,dexprs[g]] + map(isZero,dcounts[g])
TypeError: can only concatenate list (not "map") to list

**Comment by ldiao** [comment]
Hi LliliansCalvo,

I've just returned from the Thanksgiving holiday and can try to take a look
at this issue tonight after I get home from work.

Thanks,
Liyang

**Comment by kcchen88** [comment]
Hi, this sounds like it might be a Python 2 vs. Python 3 issue to me?


Kevin

________________________________

**Comment by LliliansCalvo** [comment]
Thanks Kevin, 

I repeat it all using a different computer (with Python version 2.7)
However, I am still getting an error, a different one this time. 

Toms-iMac:MixMir-master tompettini$ python MixMir.py --seqf testdat/test-utrs.fa --exprf testdat/test-exprs.txt --mirf testdat/testmirs.fa --k_kin 6 --k_motif 6 --N 20 --fast 0 --out testdat/test
Solving MLM with GEMMA
Parsing files for PLINK
Removing 418 motifs with no information
Removing 418 motifs with no information
Finished parsing files!
Running PLINK...........................
sh: ./plink: No such file or directory
PLINK files generated!
Solving MLM.................
sh: ./gemma-0.94: cannot execute binary file
sh: ./gemma-0.94: cannot execute binary file
MLM solve complete!
Analyzing results.......................
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 31, in doAll
    getResults()
  File "MixMir.py", line 89, in getResults
    analyze.doAll(resFile=resFile,mirFile=mirf,seqFile=seqf,N=Nkeep,useFast=useFast,outfn=resf)
  File "/Users/tompettini/Desktop/MixMir-master/analyze.py", line 34, in doAll
    res = loadGemmaRes(f=resFile,reverse=True)
  File "/Users/tompettini/Desktop/MixMir-master/analyze.py", line 141, in loadGemmaRes
    gem = read(f)
  File "/Users/tompettini/Desktop/MixMir-master/analyze.py", line 54, in read
    ifile = open(f,'r')
IOError: [Errno 2] No such file or directory: 'output/test.assoc.txt'

This command produced 3 different files : 

- kin.txt
- .ped
- .map 

Thanks again, 
Llilians

**Comment by ldiao** [comment]
​Hi Llilians,

I was able to run the example provided without an issue, using the command
you included above. Based on the error messages, did you make sure to chmod
+x gemma-0.94?

**Comment by LliliansCalvo** [comment]
Hi Idiao, 

I did chmod +x gemma-0.94 in both computers I tried. 

Thanks !

**Comment by ldiao** [comment]
Did you put a symlink of the plink executable in the same directory as MixMir.py? You can test to make sure plink is working first by running 

./plink --noweb

This should bring up the PLINK welcome/startup message (see below). 

Here is an example of output I get when running the example command, which shows PLINK starting up and running first.

@----------------------------------------------------------@
|        PLINK!       |     v1.07      |   10/Aug/2009     |
|----------------------------------------------------------|
|  (C) 2009 Shaun Purcell, GNU General Public License, v2  |
|----------------------------------------------------------|
|  For documentation, citation & bug-report instructions:  |
|        http://pngu.mgh.harvard.edu/purcell/plink/        |
@----------------------------------------------------------@

Skipping web check... [ --noweb ]
Writing this text to log file [ testdat/test.log ]
Analysis started: Wed Nov 29 19:20:47 2017

Options in effect:
        --noweb
        --make-bed
        --file testdat/test
        --no-fid
        --no-parents
        --no-sex
        --map3
        --out testdat/test

3678 (of 3678) markers to be included from [ testdat/test.map ]
Warning, found 24 individuals with ambiguous sex codes
Writing list of these individuals to [ testdat/test.nosex ]
24 individuals read from [ testdat/test.ped ]
24 individuals with nonmissing phenotypes
Assuming a quantitative trait
Missing phenotype value is -9
0 males, 0 females, and 24 of unspecified sex
Before frequency and genotyping pruning, there are 3678 SNPs
24 founders and 0 non-founders found
Total genotyping rate in remaining individuals is 1
0 SNPs failed missingness test ( GENO > 1 )
0 SNPs failed frequency test ( MAF < 0 )
After frequency and genotyping pruning, there are 3678 SNPs
After filtering, 24 individuals with non-missing status
After filtering, 0 males, 0 females, and 24 of unspecified sex
Writing pedigree information to [ testdat/test.fam ]
Writing map (extended format) information to [ testdat/test.bim ]
Writing genotype bitfile to [ testdat/test.bed ]
Using (default) SNP-major mode

Analysis finished: Wed Nov 29 19:20:47 2017

Reading Files ...
## number of total individuals = 24
## number of analyzed individuals = 24
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 3678
Start Eigen-Decomposition...
Reading Files ...
## number of total individuals = 24
## number of analyzed individuals = 24
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 3678
## number of analyzed SNPs = 3678
pve estimate =0.999988
se(pve) =9.6319e-06
Reading SNPs                                                    0.00%^MReading SNPs  ==================================================100.00%
Solving MLM with GEMMA
Parsing files for PLINK
Removing 418 motifs with no information
Removing 418 motifs with no information
Finished parsing files!
Running PLINK...........................
PLINK files generated!
Solving MLM.................
MLM solve complete!
Analyzing results.......................
(12, 'of', 20, 'entries matched')
Writing MixMir results to testdat/test-MixMir-results.txt.gemma
Analysis complete!

**Comment by ldiao** [comment]
I can reproduce your error if there is no plink in the working directory, so I suspect this is the error:

(venv27) bash-4.2$ python MixMir.py --seqf testdat/test-utrs.fa --exprf testdat/test-exprs.txt --mirf testdat/testmirs.fa --k_kin 6 --k_motif 6 --N 20 --fast 0 --out testdat/test_noplink
Solving MLM with GEMMA
Parsing files for PLINK
Removing 418 motifs with no information
Removing 418 motifs with no information
Finished parsing files!
Running PLINK...........................
sh: ./plink: No such file or directory
PLINK files generated!
Solving MLM.................
error! fail to open .bim file: testdat/test_noplink.bim
error! fail to open .bed file: testdat/test_noplink.bed
error! fail to open .fam file: testdat/test_noplink.fam
error! fail to open .bim file: testdat/test_noplink.bim
error! fail to open .bed file: testdat/test_noplink.bed
error! fail to open .fam file: testdat/test_noplink.fam
MLM solve complete!
Analyzing results.......................
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 31, in doAll
   getResults()
  File "MixMir.py", line 89, in getResults
    analyze.doAll(resFile=resFile,mirFile=mirf,seqFile=seqf,N=Nkeep,useFast=useFast,outfn=resf)
  File "/volumes/spore_storage/home/ldiao/Misc/MixMir/analyze.py", line 34, in doAll
    res = loadGemmaRes(f=resFile,reverse=True)
  File "/volumes/spore_storage/home/ldiao/Misc/MixMir/analyze.py", line 141, in loadGemmaRes
    gem = read(f)
  File "/volumes/spore_storage/home/ldiao/Misc/MixMir/analyze.py", line 54, in read
    ifile = open(f,'r')
IOError: [Errno 2] No such file or directory: 'output/test_noplink.assoc.txt'

**Comment by LliliansCalvo** [comment]
Thanks,

Maybe you are right and is Plink the error, but I have no idea how to fix it. It seems like something is missing 

l-u-c02sl2h9gg78:MixMir-master llilians$ ./plink --noweb

@----------------------------------------------------------@
|        PLINK!       |     v1.07      |   10/Aug/2009     |
|----------------------------------------------------------|
|  (C) 2009 Shaun Purcell, GNU General Public License, v2  |
|----------------------------------------------------------|
|  For documentation, citation & bug-report instructions:  |
|        http://pngu.mgh.harvard.edu/purcell/plink/        |
@----------------------------------------------------------@

Skipping web check... [ --noweb ] 
Writing this text to log file [ plink.log ]
Analysis started: Thu Nov 30 10:42:15 2017

Options in effect:
	--noweb

Before frequency and genotyping pruning, there are 0 SNPs
0 founders and 0 non-founders found
0 SNPs failed missingness test ( GENO > 1 )
0 SNPs failed frequency test ( MAF < 0 )
After frequency and genotyping pruning, there are 0 SNPs

ERROR: Stopping as there are no SNPs left for analysis

**Comment by LliliansCalvo** [comment]
Working on another computer (Linux) the problem has been solved. Your example runs smoothly 👍 
However, when I run my own file the error persist 

python MixMir.py --seqf 13_brief-names_utr3p.fa --exprf test-exprs-copy.txt --mirf arthropods-mature.fa --k_kin 6 --k_motif 6 --N 50 --fast 0 --out results-13-utr3p

Solving MLM with GEMMA
Parsing files for PLINK
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 18, in doAll
    runParse(doKin=doKin)
  File "MixMir.py", line 43, in runParse
    parseAll.doAll(doKin=doKin,seqf=seqf,exprf=exprf,outfnkin=kinf,outPedFile=outPedFile,outMapFile=outMapFile,kkin=kkin,kmotif=kmotif,frac=frac,useFast=useFast)
  File "/home/ana/mixmir/MixMir-master/parseAll.py", line 49, in doAll
    dutrs = makeFaDict(utrs)
  File "/home/ana/mixmir/MixMir-master/parseAll.py", line 125, in makeFaDict
    if row[0] == '>':
**IndexError: string index out of range**


This is how my files look like, I have modified them to look more like yours: 

- fasta utr3p
>ame_refGene_NM_001008533 strand=+
GAACGA...
>bmo_refGene_NM_001029878 strand=+
TTTAGTTTTCC...
>dme_refGene_NM_001039510 strand=+
GCCCGCGATCC...
(13 UTRs in total) 
(For some reasons when I post this the '>' will disappear from the post, but they are in the file (ex: >ame_refGene_NM_001008533 strand=+
GAACGA...)

- ID file 
NM_001008533	-0.01531657
NM_001039510	-0.12028854
NM_001160371	-0.01531657


- microRNAs mature sequences (fro mirbase)
>aae-miR-184
UGGACGGAGAACUGAUAAGGGC
>aae-miR-275-5p
CGCGCUAAGCAGGAACCGAGAC
 etc 



Sorry for bothering, 
Thanks !

**Comment by ldiao** [comment]
Can you try replacing U with T in your microRNAs file to see if that works?
Also to reiterate Kevin's comment previously, make sure to have the > in
the fasta files (including miRNA file).

**Comment by LliliansCalvo** [comment]
Thanks again for the help !

MixMir now working, moreover thanks for the advice Idiao, the miR file does need to have T instead of U.
