### ISSUE TITLE
error when running test data 

### ISSUE THREAD

**Issue by LliliansCalvo** [ldiao/MixMir#5]
Hi I have installed MixMir and I keep getting this error when trying to run the testate but I don't know how to solve it. Any idea what could it be?

python MixMir.py --seqf testdat/test-utrs.fa --exprf testdat/test-exprs.txt --mirf testdat/testmirs.fa --k_kin 6 --k_motif 6 --N 20 --fast 0
Solving MLM with GEMMA
Parsing files for PLINK
Removing 418 motifs with no information
Removing 418 motifs with no information
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 18, in doAll
    runParse(doKin=doKin)
  File "MixMir.py", line 43, in runParse
    parseAll.doAll(doKin=doKin,seqf=seqf,exprf=exprf,outfnkin=kinf,outPedFile=outPedFile,outMapFile=outMapFile,kkin=kkin,kmotif=kmotif,frac=frac,useFast=useFast)
  File "/mnt/fls01-home01/mqbpwlc2/privatemodules/MixMir/parseAll.py", line 76, in doAll
    makePed(genes=genes,dcounts=dcounts,dexprs=dexprs,outfn=outPedFile)
  File "/mnt/fls01-home01/mqbpwlc2/privatemodules/MixMir/parseAll.py", line 281, in makePed
    newrow = [g,dexprs[g]] + map(isZero,dcounts[g])
TypeError: can only concatenate list (not "map") to list

python --version
Python 3.7.3

**Comment by ldiao** [comment]
Hi Gilly,

I have not been maintaining this software, but my hunch is that python 3
doesn't like the syntax. This was written for python 2. Please give that a
try and see if it works.

Thanks,
Liyang

**Comment by LliliansCalvo** [comment]
Hi, 
Thanks for you answer. I tried with python2.7 and still I am getting errors 

 python2.7 MixMir.py  --seqf testdat/test-utrs.fa --exprf testdat/test-exprs.txt --mirf testdat/testmirs.fa --k_kin 6 --k_motif 6 --N 20 --fast 0
Solving MLM with GEMMA
Parsing files for PLINK
Removing 418 motifs with no information
Removing 418 motifs with no information
Finished parsing files!
Running PLINK...........................

@----------------------------------------------------------@
|        PLINK!       |     v1.07      |   10/Aug/2009     |
|----------------------------------------------------------|
|  (C) 2009 Shaun Purcell, GNU General Public License, v2  |
|----------------------------------------------------------|
|  For documentation, citation & bug-report instructions:  |
|        http://pngu.mgh.harvard.edu/purcell/plink/        |
@----------------------------------------------------------@

Skipping web check... [ --noweb ] 
Writing this text to log file [ MixMir-out.log ]
Analysis started: Sun Oct 11 23:03:49 2020

Options in effect:
	--noweb
	--make-bed
	--file MixMir-out
	--no-fid
	--no-parents
	--no-sex
	--map3
	--out MixMir-out

3678 (of 3678) markers to be included from [ MixMir-out.map ]
Warning, found 24 individuals with ambiguous sex codes
Writing list of these individuals to [ MixMir-out.nosex ]
24 individuals read from [ MixMir-out.ped ] 
24 individuals with nonmissing phenotypes
Assuming a quantitative trait
Missing phenotype value is -9
0 males, 0 females, and 24 of unspecified sex
Before frequency and genotyping pruning, there are 3678 SNPs
24 founders and 0 non-founders found
Total genotyping rate in remaining individuals is 1
0 SNPs failed missingness test ( GENO > 1 )
0 SNPs failed frequency test ( MAF < 0 )
After frequency and genotyping pruning, there are 3678 SNPs
After filtering, 24 individuals with non-missing status
After filtering, 0 males, 0 females, and 24 of unspecified sex
Writing pedigree information to [ MixMir-out.fam ] 
Writing map (extended format) information to [ MixMir-out.bim ] 
Writing genotype bitfile to [ MixMir-out.bed ] 
Using (default) SNP-major mode

Analysis finished: Sun Oct 11 23:03:50 2020

PLINK files generated!
Solving MLM.................
Reading Files ... 
## number of total individuals = 24
## number of analyzed individuals = 24
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 3678
## number of analyzed SNPs = 3678
Start Eigen-Decomposition...
Reading Files ... 
## number of total individuals = 24
## number of analyzed individuals = 24
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 3678
## number of analyzed SNPs = 3678
pve estimate =0.999988
se(pve) =9.6319e-06
Reading SNPs  ==================================================100.00%
MLM solve complete!
Analyzing results.......................
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 31, in doAll
    getResults()
  File "MixMir.py", line 89, in getResults
    analyze.doAll(resFile=resFile,mirFile=mirf,seqFile=seqf,N=Nkeep,useFast=useFast,outfn=resf)
  File "/Users/user/bin/MixMir/analyze.py", line 34, in doAll
    res = loadGemmaRes(f=resFile,reverse=True)
  File "/Users/user/bin/MixMir/analyze.py", line 147, in loadGemmaRes
    gem = [[revcomp(row[1]),float(row[-1]),float(row[4])] for row in gem]
ValueError: could not convert string to float: A

**Comment by LliliansCalvo** [comment]
Solved, it was some numpy problem in python2.7.
